import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import Ajv from 'ajv'
import { evaluate } from '../s3-s7.mjs'
import { parse } from 'yaml'

const bytes = (value) => Buffer.from(value, 'utf8')
const input = (value) => ({ param: 'contract_paths', index: 0, sha256: createHash('sha256').update(bytes(value)).digest('hex'), size: bytes(value).length, encoding: 'base64', content: bytes(value).toString('base64') })
const base = () => ({ contract_intake_receipt: { intake_id: 'INTAKE-20260913-a1b2c3d4', verdict: 'passed', verdict_label: '通过', verdict_basis: 'candidate', object: { contract_object_id: 'C01', object_title: 'demo', submission_mode: 'single' }, input_inventory: { submission_inventory_manifest_digest: 'unknown', current_contract_manifest_digest: 'unknown' }, scope: { submitted_file_paths: ['C:/authorized/c01.md'], parts: [{ id: 'body' }] }, freeze: { master_version: { frozen: true }, page_range: { frozen: true, parts: [] }, attachment_manifest: { frozen: true, status: 'no_attachments', declared: [], referenced: [], delivered: [] }, execution_status: { frozen: true, verification_status: 'not_performed', parties: [] } }, all_frozen: true, consistency_conclusion_allowed: true, checks: ['S1','S2','S3','S4','S5','S6','S7','S8'].map((id) => ({ id, name: id, status: 'pass' })), blocks: [], flags: [], version_matrix: { status: 'aligned' }, alignment_advice: [], human_gate: [], remediation: [], handoff: { to: 'clause-extractor', from: 'contract-intake', case_id: 'C01', intake_id: 'INTAKE-20260913-a1b2c3d4', receipt_path: 'C:/authorized/out.receipt.yaml', object: { contract_object_id: 'C01', object_title: 'demo', submission_mode: 'single' }, input_inventory: { submission_inventory_manifest_digest: 'unknown', current_contract_manifest_digest: 'unknown' }, confirmed: [], pending: [], scope: { in_scope: [], out_of_scope: [] }, do_not_pass: [] } } })
const run = (content, receipt = base()) => { const i = input(content); return evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: receipt, parts: [{ sha256: i.sha256, part: 'body' }] }, inputs: [i], output: { param: 'output_path' } }).contract_intake_receipt }
const localZip = (name, content) => { const nameBytes = Buffer.from(name); const data = Buffer.from(content); const header = Buffer.alloc(30); header.writeUInt32LE(0x04034b50, 0); header.writeUInt16LE(20, 4); header.writeUInt16LE(0, 6); header.writeUInt16LE(0, 8); header.writeUInt32LE(data.length, 18); header.writeUInt32LE(data.length, 22); header.writeUInt16LE(nameBytes.length, 26); return Buffer.concat([header, nameBytes, data]) }
const toolDir = path.dirname(fileURLToPath(import.meta.url))

test('recomputes continuous pages and exact matching paired amounts from snapshot bytes', () => { const receipt = run('第 1 页 / 共 2 页\n人民币壹佰元整（¥100.00）\n第 2 页 / 共 2 页'); assert.equal(receipt.verdict, 'passed'); assert.equal(receipt.checks.find((x) => x.id === 'S3').status, 'pass'); assert.equal(receipt.checks.find((x) => x.id === 'S7').status, 'pass') })
test('rejects candidate-derived S3/S7 pass data on missing, duplicate, and mismatched source facts', () => { const receipt = run('第 1 页 / 共 2 页\n第 1 页 / 共 2 页\n人民币壹佰元整（¥101.00）'); assert.equal(receipt.verdict, 'blocked'); assert.ok(receipt.blocks.some((x) => x.code === 'BLK-PAGE-DUPLICATE')); assert.ok(receipt.flags.some((x) => x.code === 'FLG-AMOUNT-IN-WORDS-MISMATCH')) })
test('holds when snapshot identity changes or a DOCX source is unsupported', () => { const i = input('第 1 页 / 共 1 页'); i.sha256 = '0'.repeat(64); const receipt = base(); const output = evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: receipt, parts: [{ sha256: i.sha256, part: 'body' }] }, inputs: [i], output: { param: 'output_path' } }).contract_intake_receipt; assert.equal(output.verdict, 'blocked'); assert.ok(output.blocks.some((x) => x.code === 'BLK-DETERMINISTIC-SOURCE_HASH_MISMATCH')); const zip = Buffer.from([0x50, 0x4b, 3, 4]); const docxInput = { param: 'contract_paths', index: 0, sha256: createHash('sha256').update(zip).digest('hex'), size: zip.length, encoding: 'base64', content: zip.toString('base64') }; const docx = evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: base(), parts: [{ sha256: docxInput.sha256, part: 'body' }] }, inputs: [docxInput], output: { param: 'output_path' } }).contract_intake_receipt; assert.equal(docx.verdict, 'blocked') })
test('preserves noncomputed source facts and a false freeze while recomputing the typed AND', () => { const receipt = base(); receipt.contract_intake_receipt.freeze.master_version.frozen = false; receipt.contract_intake_receipt.freeze.master_version.contract_no = 'raw-observation'; const output = run('第 1 页 / 共 1 页', receipt); assert.equal(output.freeze.master_version.contract_no, 'raw-observation'); assert.equal(output.all_frozen, false); assert.equal(output.verdict, 'conditional') })
test('rejects ambiguous part bindings and preserves a source-anchored party block in S7', () => { const i = input('第 1 页 / 共 1 页'); const candidate = base(); candidate.contract_intake_receipt.blocks.push({ code: 'BLK-PARTY-INCONSISTENT', gate_reason_id: 'party-name-inconsistency', severity: 'block', clause: null, evidence: { part: 'body', page: null, quote: 'party mismatch' }, finding: 'Party mismatch.', action: 'Correct party.' }); const party = evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: candidate, parts: [{ sha256: i.sha256, part: 'body' }] }, inputs: [i], output: { param: 'output_path' } }).contract_intake_receipt; assert.equal(party.checks.find((x) => x.id === 'S7').status, 'block'); const duplicate = evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: base(), parts: [{ sha256: i.sha256, part: 'body' }, { sha256: i.sha256, part: 'attachment:A1' }] }, inputs: [i], output: { param: 'output_path' } }).contract_intake_receipt; assert.ok(duplicate.blocks.some((x) => x.code === 'BLK-DETERMINISTIC-PART_BINDING_INVALID')) })
test('holds when receipt scope parts omit, add, or duplicate a snapshot mapping', () => { const i = input('第 1 页 / 共 1 页'); for (const parts of [[], [{ id: 'body' }, { id: 'attachment:A1' }], [{ id: 'body' }, { id: 'body' }]]) { const candidate = base(); candidate.contract_intake_receipt.scope.parts = parts; const receipt = evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: candidate, parts: [{ sha256: i.sha256, part: 'body' }] }, inputs: [i], output: { param: 'output_path' } }).contract_intake_receipt; assert.equal(receipt.verdict, 'blocked'); assert.ok(receipt.blocks.some((x) => x.code === 'BLK-DETERMINISTIC-SCOPE_PARTS_INVALID')) } })
test('checks the documented RMB SAY pairing exactly', () => { const receipt = run('第 1 页 / 共 1 页\nRMB 101.00 (SAY 壹佰元整 ONLY)'); assert.ok(receipt.flags.some((x) => x.code === 'FLG-AMOUNT-IN-WORDS-MISMATCH')) })
test('uses explicit 角/分 units and rejects malformed uppercase amount grammar', () => { for (const [arabic, upper] of [['0.05', '零元伍分'], ['0.50', '零元伍角'], ['0.53', '零元伍角叁分'], ['10000.00', '壹万元整']]) { const receipt = run(`第 1 页 / 共 1 页\n人民币${upper}（¥${arabic}）`); assert.equal(receipt.checks.find((x) => x.id === 'S7').status, 'pass', upper) } const cents = run('第 1 页 / 共 1 页\n人民币零元伍分（¥0.50）'); assert.ok(cents.flags.some((x) => x.code === 'FLG-AMOUNT-IN-WORDS-MISMATCH')); for (const invalid of ['壹万亿元整', '壹贰元整']) { const receipt = run(`第 1 页 / 共 1 页\n人民币${invalid}（¥10000.00）`); assert.equal(receipt.verdict, 'blocked', invalid); assert.ok(receipt.blocks.some((x) => x.code === 'BLK-DETERMINISTIC-AMOUNT_UNCERTAIN'), invalid) } })
test('holds a syntactically valid DOCX local entry that carries a dynamic PAGE field', () => { const zip = localZip('word/document.xml', '<w:document><w:fldSimple w:instr=" PAGE "/><w:t>第 1 页 / 共 1 页</w:t></w:document>'); const i = { param: 'contract_paths', index: 0, sha256: createHash('sha256').update(zip).digest('hex'), size: zip.length, encoding: 'base64', content: zip.toString('base64') }; const receipt = evaluate({ protocol: 'desirecore.script.snapshot.v1', params: { receipt_base: base(), parts: [{ sha256: i.sha256, part: 'body' }] }, inputs: [i], output: { param: 'output_path' } }).contract_intake_receipt; assert.ok(receipt.blocks.some((x) => x.code === 'BLK-DETERMINISTIC-SOURCE_UNSUPPORTED')); assert.equal(receipt.verdict, 'blocked') })
test('actual deterministic output validates the release-owned receipt schema', async () => { const root = path.join(toolDir, '..', '..', '..'); const [fixture, schemaText] = await Promise.all([readFile(path.join(root, 'skills', 'contract-intake-gate', 'tests', 'fixtures', 'receipt-schema-valid.yaml'), 'utf8'), readFile(path.join(root, 'skills', 'contract-intake-gate', 'references', 'contract-intake-receipt.schema.json'), 'utf8')]); const candidate = parse(fixture); candidate.contract_intake_receipt.scope.parts = [{ id: 'body' }]; const output = run('源文件物理页1/2；印刷页码1\n人民币10,000元（大写壹万元整）\n源文件物理页2/2；印刷页码2', candidate); const validate = new Ajv({ allErrors: true, strict: true }).compile(JSON.parse(schemaText)); assert.equal(validate({ contract_intake_receipt: output }), true, JSON.stringify(validate.errors)) })
